/// Weiterbildungsbudget je Bereich und Quartal (entpivotiert)
table Budget

	column Bereich
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Bereich

	column Quartal
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: Quartal

	column Budget
		dataType: decimal
		isHidden
		formatString: #,0 €
		summarizeBy: none
		sourceColumn: Budget

	column Quartalsanfang
		dataType: dateTime
		isHidden
		formatString: dd.MM.yyyy
		summarizeBy: none
		sourceColumn: Quartalsanfang

	partition Budget = m
		mode: import
		source =
				let
				    Quelle = Excel.Workbook(Web.Contents(DatenQuelle, [RelativePath = "3-Ziele/ziele_2025.xlsx"]), null, true),
				    Blatt = Quelle{[Item = "Budget 2025", Kind = "Sheet"]}[Data],
				    OhneTitel = Table.Skip(Blatt, 2),
				    Ueberschriften = Table.PromoteHeaders(OhneTitel, [PromoteAllScalars = true]),
				    OhneGesamtzeile = Table.SelectRows(Ueberschriften, each [Bereich] <> "Gesamt"),
				    OhneSummenspalte = Table.RemoveColumns(OhneGesamtzeile, {"Summe"}),
				    Entpivotiert = Table.UnpivotOtherColumns(OhneSummenspalte, {"Bereich"}, "Quartal", "Budget"),
				    Quartalsanfang = Table.AddColumn(Entpivotiert, "Quartalsanfang", each #date(2025, (Number.From(Text.End([Quartal], 1)) - 1) * 3 + 1, 1), type date),
				    Typen = Table.TransformColumnTypes(Quartalsanfang, {{"Bereich", type text}, {"Quartal", type text}, {"Budget", Currency.Type}})
				in
				    Typen

