/// Kurskatalog
table dim_kurs

	column Kursnr
		dataType: string
		summarizeBy: none
		sourceColumn: Kursnr

	column Kurstitel
		dataType: string
		summarizeBy: none
		sourceColumn: Kurstitel

	column Kategorie
		dataType: string
		summarizeBy: none
		sourceColumn: Kategorie

	column Format
		dataType: string
		summarizeBy: none
		sourceColumn: Format

	column Anbieter
		dataType: string
		summarizeBy: none
		sourceColumn: Anbieter

	column Pflicht
		dataType: string
		summarizeBy: none
		sourceColumn: Pflicht

	column Dauer_h
		dataType: double
		formatString: #,0.0
		summarizeBy: none
		sourceColumn: Dauer_h

	column Listenpreis
		dataType: decimal
		formatString: #,0.00 €
		summarizeBy: none
		sourceColumn: Listenpreis

	partition dim_kurs = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(Web.Contents(DatenQuelle, [RelativePath = "2-Anreicherung/dim_kurs.csv"]), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Ueberschriften = Table.PromoteHeaders(Quelle, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Ueberschriften, {{"Kursnr", type text}, {"Kurstitel", type text}, {"Kategorie", type text}, {"Format", type text}, {"Anbieter", type text}, {"Pflicht", type text}, {"Dauer_h", type number}, {"Listenpreis", Currency.Type}}, "en-US")
				in
				    Typen

