/// HR-Stamm, eine Zeile je Person (pseudonymisiert)
table dim_mitarbeitende

	column Personalnr
		dataType: string
		summarizeBy: none
		sourceColumn: Personalnr

	column BereichID
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: BereichID

	column Standort
		dataType: string
		summarizeBy: none
		sourceColumn: Standort

	column Rolle
		dataType: string
		summarizeBy: none
		sourceColumn: Rolle

	column Beschaeftigung
		dataType: string
		summarizeBy: none
		sourceColumn: Beschaeftigung

	column FTE
		dataType: double
		isHidden
		formatString: 0.00
		summarizeBy: none
		sourceColumn: FTE

	column Altersgruppe
		dataType: string
		summarizeBy: none
		sourceColumn: Altersgruppe

	column Eintritt
		dataType: dateTime
		formatString: dd.MM.yyyy
		summarizeBy: none
		sourceColumn: Eintritt

	partition dim_mitarbeitende = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(Web.Contents(DatenQuelle, [RelativePath = "anreicherung/dim_mitarbeitende.csv"]), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Ueberschriften = Table.PromoteHeaders(Quelle, [PromoteAllScalars = true]),
				    Typen = Table.TransformColumnTypes(Ueberschriften, {{"Personalnr", type text}, {"BereichID", type text}, {"Standort", type text}, {"Rolle", type text}, {"Beschaeftigung", type text}, {"FTE", type number}, {"Altersgruppe", type text}, {"Eintritt", type date}}, "en-US")
				in
				    Typen

